# Generated by Django 3.1.5 on 2022-08-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_holders',
            name='coupon',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Kupon kodu'),
        ),
    ]
