# Generated by Django 3.1.5 on 2022-08-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20220808_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='including',
            field=models.IntegerField(default=0, verbose_name='Minimum sifariş AZN'),
        ),
    ]
