# Generated by Django 3.1.5 on 2022-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_coupons_including'),
    ]

    operations = [
        migrations.CreateModel(
            name='Min_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Minimum sifariş AZN ilə')),
            ],
        ),
    ]
