# Generated by Django 3.1.5 on 2022-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_min_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='min_order',
            options={'verbose_name': 'Minimum sifariş', 'verbose_name_plural': 'Minimum sifariş'},
        ),
    ]
