# Generated by Django 3.1.5 on 2022-08-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_min_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='min_order',
            name='name',
            field=models.CharField(default='Redaktə et', max_length=50, verbose_name='Minimum sifariş'),
        ),
    ]
