# Generated by Django 3.1.5 on 2022-08-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20220809_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='min_order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Çatdırılma qiyməti AZN ilə'),
        ),
    ]
