# Generated by Django 3.1.5 on 2022-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_min_order_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='min_order',
            options={'verbose_name': 'Çatdırılma', 'verbose_name_plural': 'Çatdırılma'},
        ),
        migrations.AlterField(
            model_name='min_order',
            name='name',
            field=models.CharField(default='Redaktə et', max_length=50, verbose_name='Pulsuz Çatdırılma minimum sifariş'),
        ),
    ]
