# Generated by Django 3.1.5 on 2021-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_merge_20210612_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='color_black',
            field=models.BooleanField(default=False, verbose_name='Qara'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_blue',
            field=models.BooleanField(default=False, verbose_name='Mavi'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_green',
            field=models.BooleanField(default=False, verbose_name='Yaşıl'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_grey',
            field=models.BooleanField(default=False, verbose_name='Boz'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_mix',
            field=models.BooleanField(default=False, verbose_name='Qarışıq'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_orange',
            field=models.BooleanField(default=False, verbose_name='Narıncı'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_pink',
            field=models.BooleanField(default=False, verbose_name='Çəhrayı'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_purple',
            field=models.BooleanField(default=False, verbose_name='Bənövşəyi'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_red',
            field=models.BooleanField(default=False, verbose_name='Qırmızı'),
        ),
        migrations.AddField(
            model_name='basket',
            name='color_yellow',
            field=models.BooleanField(default=False, verbose_name='Sarı'),
        ),
    ]
