# Generated by Django 3.1.5 on 2022-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20220809_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='min_order',
            name='name',
            field=models.CharField(default='Redaktə et', max_length=50, verbose_name='Pulsuz Çatdırılma'),
        ),
    ]
