# Generated by Django 3.1.5 on 2022-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20211006_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_holders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(max_length=100)),
                ('coupon', models.CharField(default=None, max_length=50, null=True, verbose_name='Kupon kodu')),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(default=None, max_length=50, null=True, verbose_name='Kupon kodu')),
                ('discount', models.IntegerField(default=0, max_length=100, verbose_name='Endirim faizi')),
            ],
            options={
                'verbose_name': 'Kuponlar',
                'verbose_name_plural': 'Kuponlar',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon_code',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Kupon kodu'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Endirim'),
        ),
    ]
