# Generated by Django 3.1.5 on 2022-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20220808_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Endirim faizi'),
        ),
    ]
