# Generated by Django 3.1.5 on 2022-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_coupons_including'),
        ('basket', '0003_coupons_including'),
    ]

    operations = [
    ]
