# Generated by Django 3.1.5 on 2022-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0015_merge_20220809_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Min_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Redaktə et', max_length=50, verbose_name='Pulsuz Çatdırılma')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='Çatdırılma haqqı AZN ilə')),
                ('price', models.IntegerField(default=0, verbose_name='Pulsuz çatdırılma üçün minimum sifariş AZN ilə')),
            ],
            options={
                'verbose_name': 'Çatdırılma',
                'verbose_name_plural': 'Çatdırılma',
            },
        ),
    ]
