# Generated by Django 3.1.5 on 2021-10-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20211006_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color_s',
        ),
        migrations.AddField(
            model_name='products',
            name='color_s',
            field=models.ManyToManyField(null=True, to='products.Colors'),
        ),
    ]
