# Generated by Django 3.1.5 on 2021-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20211006_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_black',
            field=models.BooleanField(default=False, verbose_name='Qara'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_blue',
            field=models.BooleanField(default=False, verbose_name='Mavi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_green',
            field=models.BooleanField(default=False, verbose_name='Yaşıl'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_grey',
            field=models.BooleanField(default=False, verbose_name='Boz'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_orange',
            field=models.BooleanField(default=False, verbose_name='Narıncı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_pink',
            field=models.BooleanField(default=False, verbose_name='Çəhrayı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_purple',
            field=models.BooleanField(default=False, verbose_name='Bənövşəyi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_red',
            field=models.BooleanField(default=False, verbose_name='Qırmızı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_yellow',
            field=models.BooleanField(default=False, verbose_name='Sarı'),
        ),
    ]
