# Generated by Django 3.1.5 on 2021-10-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20211006_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color_black',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_blue',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_green',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_grey',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_orange',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_pink',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_purple',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_red',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color_yellow',
        ),
    ]
