# Generated by Django 3.1.5 on 2021-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20211006_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color_mix',
            field=models.BooleanField(default=False, verbose_name='Qarışıq'),
        ),
    ]
