# Generated by Django 3.1.5 on 2021-10-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20211006_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
