# Generated by Django 3.1.5 on 2021-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.BooleanField(choices=[(0, 'Standart'), (1, 'Qarışıq')], default=0, max_length=15, verbose_name='Rəng tipi'),
        ),
    ]
