# Generated by Django 3.1.5 on 2021-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.BooleanField(choices=[(0, 'Standart'), (1, 'Rəngli')], default=0, help_text='Əgər məhsulun rəngləri varsa RƏNGLİ seç və aşağıdan rəngləri seç. Əksi halda standart seç', max_length=15, verbose_name='Rəng tipi'),
        ),
    ]
