# Generated by Django 3.1.5 on 2021-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20211007_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('İnterdental fırçalar', (('original', 'Orijinal'), ('extra_soft', 'Eksta yumşaq'), ('angle', 'Dönəcəkli'))), ('toothpicks', 'Kürdan'), ('dental_floss', 'Diş ipi'), ('brushers', (('adult', 'Böyüklər üçün'), ('kids', 'Uşaqlar üçün'))), ('accesories', 'Aksesuarlar')], max_length=30, verbose_name='Kateqoriya'),
        ),
    ]
