# Generated by Django 3.1.5 on 2021-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20211007_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('interdental', 'Dişarası fırçalar'), ('toothpicks', 'Kürdan'), ('dental_floss', 'Diş ipi'), ('brushers', 'Diş fırçaları'), ('accesories', 'Aksesuarlar')], max_length=30, verbose_name='Kateqoriya'),
        ),
    ]
