# Generated by Django 3.1.5 on 2021-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20211007_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='company',
            field=models.CharField(choices=[('all', 'Ümumi'), ('tepe', 'TePe'), ('bilimplant', 'Bilimplant'), ('miradent', 'Miradent'), ('aquapick', 'Aquapick')], default='all', help_text='Hansı saytda görünməsini istəyirsən?', max_length=15, null=True, verbose_name='Firma'),
        ),
    ]
